**1. Array Creation & Properties**

In [2]:
#1. Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("shape: " , arr.shape)
print("size: " , arr.size)
print("Datatype: " , arr.dtype)

shape:  (5,)
size:  5
Datatype:  int64


In [3]:
#2. Create a 3 × 4 array containing numbers from 1 to 12.
arr = np.arange(1,13,1)
arr = arr.reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
#3. Create an array of zeros, an array of ones, and an identity matrix.
zero_mat = np.zeros((3,3))
ones_mat = np.ones((3,3))
identity_mat = np.eye(3)
print("zero matrix: \n" , zero_mat)
print("ones matrix: \n" , ones_mat)
print("identity matrix: \n" , identity_mat)

zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#4. Generate all even numbers between 10 and 50 using np.arange().
even_numbers = np.arange(10 , 51 , 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
#5. Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
arr = np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**2. Array Arithmetic**

In [7]:
#Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.
a = np.array([10,20,30,40])
b = np.array([50,60,70,80])
print("Addition: " , a+b)
print("Substraction: " , a-b)
print("Multiplication: " , a*b)
print("Division: " , a/b)

Addition:  [ 60  80 100 120]
Substraction:  [-40 -40 -40 -40]
Multiplication:  [ 500 1200 2100 3200]
Division:  [0.2        0.33333333 0.42857143 0.5       ]


In [8]:
#7. Calculate the square and cube of every element in a NumPy array.
arr = np.array([10,20,30,40,50,60])

square = arr*arr
cube = arr*arr*arr

print("square: ", square)
print("cube: ", cube)

square:  [ 100  400  900 1600 2500 3600]
cube:  [  1000   8000  27000  64000 125000 216000]


In [9]:
#8. Increase every element of an array by 15%.

arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr = arr * 1.15

print(arr)

[ 11.5  23.   34.5  46.   57.5  69.   80.5  92.  103.5 115. ]


In [10]:
#9. Given two arrays, find their element-wise maximum and minimum.

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([15, 18, 35, 25])

maximum = np.maximum(arr1, arr2)
minimum = np.minimum(arr1, arr2)

print("Element-wise maximum:", maximum)
print("Element-wise minimum:", minimum)

Element-wise maximum: [15 20 35 40]
Element-wise minimum: [10 18 30 25]


**3. Indexing & Slicing**

In [11]:
#10. Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.

arr = np.arange(0, 21)

print("Array:", arr)

# First five elements
print("First five:", arr[:5])

# Last five elements
print("Last five:", arr[-5:])

# Elements from index 5 to 15
print("Index 5 to 15:", arr[5:16])

# Every second element
print("Every second element:", arr[::2])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


In [13]:
#11. Replace the first five elements of an array with 100.

arr= np.array([10,20,30,40,50,60,70,80,90])
arr[:5] = 100
print(arr)

[100 100 100 100 100  60  70  80  90]


In [14]:
#12. Create an array and demonstrate the difference between a slice/view and a copy.

arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])

# Slice / View
view = arr[1:4]

# Copy
copy = arr[1:4].copy()

print("Original array:", arr)
print("View:", view)
print("Copy:", copy)

# Change the view
view[0] = 100

print("\nAfter changing view:")
print("Original array:", arr)
print("View:", view)
print("Copy:", copy)

# Change the copy
copy[1] = 200

print("\nAfter changing copy:")
print("Original array:", arr)
print("View:", view)
print("Copy:", copy)

Original array: [ 5 10 15 20 25 30 35 40 45 50 55 60]
View: [10 15 20]
Copy: [10 15 20]

After changing view:
Original array: [  5 100  15  20  25  30  35  40  45  50  55  60]
View: [100  15  20]
Copy: [10 15 20]

After changing copy:
Original array: [  5 100  15  20  25  30  35  40  45  50  55  60]
View: [100  15  20]
Copy: [ 10 200  20]


In [26]:
#13. Reverse a NumPy array using slicing.

arr = np.array([100,150,149,416])

arr = arr[::-1]

print(arr)

[416 149 150 100]


**4. 2-D Array Indexing & Slicing**

In [28]:
#14. Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.

matrix = np.array([[10,20,30],
                   [40,50,60],
                   [70,80,90]
                  ])

print("second row: ", matrix[1])
print("third column: " , matrix[:,2])
print("element 50: " , matrix[1,1])

second row:  [40 50 60]
third column:  [30 60 90]
element 50:  50


In [29]:
#15. From the matrix above, extract the sub-matrix [[20,30],[50,60]].

subMatrix = matrix[:2 , 1:]
print(subMatrix)

[[20 30]
 [50 60]]


In [30]:
# 16. Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle element, and top-left 3 × 3 matrix.

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:" , matrix)
print("First Row:", matrix[0])
print("Last Column:", matrix[:, -1])
print("Middle Element:", matrix[2, 2])
print("Top-left 3 x 3 Matrix:" , matrix[:3, :3])

Matrix: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
Middle Element: 13
Top-left 3 x 3 Matrix: [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


**5. Reshaping & Transpose**

In [31]:
#17. Create an array containing 1–12 and reshape it into a 3 × 4 matrix.

arr = np.arange(1,13)

matrix = arr.reshape(3 , 4)

print("arr: " , arr)
print("matrix: " , matrix)

arr:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
matrix:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
#18. Reshape a 1-D array into a 2 × 5 matrix.

arr = np.array([22,25,4,5,45,6,96,8,0,50])

matrix = arr.reshape(2 , 5)

print("1D array: " , arr)
print("matrix: " , matrix)

1D array:  [22 25  4  5 45  6 96  8  0 50]
matrix:  [[22 25  4  5 45]
 [ 6 96  8  0 50]]


In [37]:
#19. Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.

matrix = np.arange(1,13).reshape(3,4)
print("Original matrix: " , matrix)

matrix = matrix.transpose()
print("Transposed matrix: " , matrix)

Original matrix:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed matrix:  [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [38]:
#20. Use transpose() and swapaxes() on a 3-D array.

arr = np.arange(1, 13).reshape(2, 2, 3)
print("Original 3-D Array:" , arr)
print("After transpose: " , arr.transpose(2, 1, 0))
print("After swapaxes(0, 2): " , arr.swapaxes(0, 2))

Original 3-D Array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After transpose:  [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
After swapaxes(0, 2):  [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


**6. Matrix Operations**




In [39]:
#21. Create two 3 × 3 matrices and perform element-wise addition and multiplication.

A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
B = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Element-wise Addition:" , A + B)
print("Element-wise Multiplication:" , A * B)

Element-wise Addition: [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
Element-wise Multiplication: [[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]


In [43]:
#22. Calculate the matrix product of two compatible matrices using np.dot().

matrix_A = np.array([[10,20],
                   [50,60]
                   ])

matrix_B = np.array([[1,2],
                   [5,6]
                   ])
matrix = np.dot(matrix_A,matrix_B)

print(matrix)

[[110 140]
 [350 460]]


In [2]:
#23. Find the transpose of a matrix and calculate its dot product with the original matrix.
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])

print("matrix: " , matrix)

transposed_matrix = matrix.transpose()

print("transposed matrix: " , transposed_matrix)

dot_product = np.dot(matrix , transposed_matrix)

print("dot product : " , dot_product)

matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
transposed matrix:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
dot product :  [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


**7. Universal Functions**

In [4]:
#24. Calculate the square root of every element in an array using NumPy.

arr = np.array([1,4,9,16,25])

print("square root: " , np.sqrt(arr))

square root:  [1. 2. 3. 4. 5.]


In [5]:
#25. Calculate e^x for every element of an array.
arr = np.array([1,4,3,2])

print("e^x: " , np.exp(arr))


e^x:  [ 2.71828183 54.59815003 20.08553692  7.3890561 ]


In [25]:
#26. Generate a random array and calculate its square root, exponential, and absolute values.

arr = np.random.randn(5)

print("random: " , arr)
print("square root: " , np.sqrt(arr))
print("e^x: " , np.exp(arr))
print("absolute value: " , np.abs(arr))

random:  [-0.99527832 -0.09150935 -1.50730282 -0.23434707 -0.62152778]
square root:  [nan nan nan nan nan]
e^x:  [0.36962056 0.91255279 0.22150662 0.7910872  0.53712321]
absolute value:  [0.99527832 0.09150935 1.50730282 0.23434707 0.62152778]


/tmp/ipykernel_504/2714794049.py:6: RuntimeWarning: invalid value encountered in sqrt
  print("square root: " , np.sqrt(arr))


In [26]:
#27. Generate two random arrays and find their element-wise maximum.

a = np.random.rand(5)
b = np.random.rand(5)
print("Array a:", a)
print("Array b:", b)
print("Element-wise Maximum:", np.maximum(a, b))

Array a: [0.0626533  0.12506444 0.80410216 0.70891348 0.4813934 ]
Array b: [0.82047947 0.50308301 0.12938411 0.54023133 0.40696167]
Element-wise Maximum: [0.82047947 0.50308301 0.80410216 0.70891348 0.4813934 ]


**8. np.where()**

In [28]:
#28. Given marks = np.array([35,72,48,90,55,28]), replace marks below 40 with 0 using np.where().

marks = np.array([35,72,48,90,55,28])
new_marks = np.where(marks < 40, 0, marks)

print(new_marks)

[ 0 72 48 90 55  0]


In [29]:
#29. Given an income array, classify observations as 'High' if income ≥ 50,000 and 'Low' otherwise.

income_array = np.array([43000, 35000, 55000, 95000, 15000, 50000])
classification = np.where(income_array >= 50000, "High", "Low")

print("Income:", income_array)
print("Classification:", classification)


Income: [43000 35000 55000 95000 15000 50000]
Classification: ['Low' 'Low' 'High' 'High' 'Low' 'High']


In [30]:
#30. Replace all values greater than 30 in an array with 100 using np.where().

arr = np.array([10,15,42,55,66,98,12,14])

after_replace = np.where(arr > 30 , 100 , arr)

print("before replace: " , arr)
print("after replace: " , after_replace)

before replace:  [10 15 42 55 66 98 12 14]
after replace:  [ 10  15 100 100 100 100  12  14]


**9. Statistical Operations**

In [32]:
#31. Given a 3 × 3 matrix, calculate its total sum, mean, variance, and standard deviation.

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])

print("Total Sum: " , np.sum(matrix))
print("Mean: " , np.mean(matrix))
print("Variance: " , np.var(matrix))
print("Standard deviation: " , np.std(matrix))

Total Sum:  45
Mean:  5.0
Variance:  6.666666666666667
Standard deviation:  2.581988897471611


In [33]:
#32. Calculate row-wise and column-wise sums using axis.

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Row-wise Sum:", np.sum(matrix, axis=1))
print("Column-wise Sum:", np.sum(matrix, axis=0))


Row-wise Sum: [ 6 15 24]
Column-wise Sum: [12 15 18]


In [35]:
#33. Given the marks of 10 students, calculate mean, standard deviation, minimum, and maximum.

marks = np.array([39,49,48,25,34,36,29,50,15,40])

print("Mean: " , np.mean(marks))
print("Standard deviation: " , np.std(marks))
print("Minimum: " , np.min(marks))
print("Maximum: " , np.max(marks))

Mean:  36.5
Standard deviation:  10.707474025184466
Minimum:  15
Maximum:  50


In [36]:
#34. Demonstrate the difference between any() and all() using a Boolean array.

arr = np.array([False, True, False, False, True])

print("Boolean Array:", arr)
print("any(): ", np.any(arr))
print("all(): ", np.all(arr))

Boolean Array: [False  True False False  True]
any():  True
all():  False


**10. Sorting & Unique Values**

In [41]:
#35. Generate 10 random numbers and sort them.

arr = np.random.randint(1 , 1000 , 10)

print("Original array: " , arr)
print("Sorted array: " , np.sort(arr))

Original array:  [888 798 804 877 370 170 816 810 543  56]
Sorted array:  [ 56 170 370 543 798 804 810 816 877 888]


In [42]:
#36. Given an array containing repeated values, find its unique elements.

arr = np.array([55,455,65,45,55,25,65,89,455])

print("All elements: " , arr)

print("Unique elements: " , np.unique(arr))

All elements:  [ 55 455  65  45  55  25  65  89 455]
Unique elements:  [ 25  45  55  65  89 455]


In [43]:
#37. Given an array of student marks, find the unique marks.

marks = np.array([39,49,48,15,34,39,29,50,15,45])

print("unique marks: " , np.unique(marks))


unique marks:  [15 29 34 39 45 48 49 50]


In [44]:
#38. Use np.in1d() to check whether selected values occur in an array.

arr = np.array([55,455,65,45,55,25,65,89,455])
selected = np.array([455, 100, 59 , 55])
result = np.isin(selected, arr)
print("Q38")
print("Original Array:", arr)
print("Selected Values:", selected)
print("Values Present:", result)

Q38
Original Array: [ 55 455  65  45  55  25  65  89 455]
Selected Values: [455 100  59  55]
Values Present: [ True False False  True]


**11. Integrated Lab Questions**

In [45]:
#39. Student Marks Analysis:
#    Create a NumPy array containing marks of 10 students in 3 subjects.
#    Calculate each student's total and average marks.
#    Identify students whose average is ≥ 50 using np.where().

marks = np.array([
    [60, 70, 80],
    [45, 50, 55],
    [30, 40, 35],
    [80, 75, 90],
    [55, 60, 50],
    [40, 45, 35],
    [90, 85, 95],
    [50, 55, 60],
    [35, 30, 40],
    [70, 65, 75]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
students = np.where(average >= 50)

print("Total marks:", total)
print("Average marks:", average)
print("Students with average >= 50:", students[0])


Total marks: [210 150 105 245 165 120 270 165 105 210]
Average marks: [70.         50.         35.         81.66666667 55.         40.
 90.         55.         35.         70.        ]
Students with average >= 50: [0 1 3 4 6 7 9]


In [48]:
#40. Matrix Analysis:
# Create a 4 × 4 matrix containing numbers 1–16.
# Find its transpose,row-wise sums, column-wise sums, mean, maximum, and minimum.
#Extract the central 2 × 2 matrix.

matrix = np.arange(1,17).reshape(4,4)

print("Transpose: " , np.transpose(matrix))
print("rowwise sum: " , np.sum(matrix , axis = 1))
print("columnwise sum: " , np.sum(matrix , axis = 0))
print("Mean: " , np.mean(matrix))
print("Maximum: " , np.max(matrix))
print("Minimum: " , np.min(matrix))
print("Central element: " , matrix[1:3 , 1:3])

Transpose:  [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
rowwise sum:  [10 26 42 58]
columnwise sum:  [28 32 36 40]
Mean:  8.5
Maximum:  16
Minimum:  1
Central element:  [[ 6  7]
 [10 11]]


In [49]:
#41. Random Data Analysis:
# Generate 20 observations using np.random.randn().
# Calculate the mean, standard deviation, minimum, maximum, and sorted values.
# Replace all negative observations with zero using np.where().

observations = np.random.randn(20)
after_replace = np.where(observations < 0, 0, observations)
print("mean: ", np.mean(observations))
print("Standard deviation: " , np.std(observations))
print("Minimum: " , np.min(observations))
print("Maximum: " , np.max(observations))
print("Sorted values: " , np.sort(observations))
print("After replace: " , after_replace)


mean:  -0.16575475792807776
Standard deviation:  1.0850474993661963
Minimum:  -1.9085620340924367
Maximum:  2.7783843722288517
Sorted values:  [-1.90856203 -1.56380308 -1.44795256 -1.03181961 -1.02394833 -0.99059443
 -0.79270308 -0.65215285 -0.53818152 -0.3518331  -0.20778444 -0.06314041
  0.20582455  0.22853711  0.55696154  0.5984163   0.8282105   0.9579895
  1.10305642  2.77838437]
After replace:  [0.         0.         0.22853711 0.20582455 0.         0.
 0.8282105  0.9579895  0.         1.10305642 0.55696154 0.
 2.77838437 0.         0.         0.         0.         0.
 0.         0.5984163 ]


In [50]:
#42. Matrix Operations Challenge:
# Create two 3 × 3 matrices and perform element-wise addition, element-wise multiplication, matrix multiplication, transpose of the first matrix,
# and maximum/minimum of the resulting matrix.

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])


print("Element-wise sum: " , A+B)
print("Element-wise multiplication" , A*B)
print("Matrix multiplication: " , np.dot(A , B))

transposed_matrix = np.transpose(A)
print("Transpose of matix A: " , transposed_matrix)
print("Minimum: " , np.min(transposed_matrix))
print("Maximum: " , np.max(transposed_matrix))


Element-wise sum:  [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of matix A:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Minimum:  1
Maximum:  9


In [52]:
#43. Array Manipulation Challenge:
# Create an array containing 1–24, reshape it into a 4 × 6 matrix, extract selected rows
# and columns, transpose it, calculate row/column statistics,
# and identify unique values.


matrix = np.arange(1,25).reshape(4,6)

print("Original matrix: " , matrix)
print("\nSelected rows (1st and 3rd):" , matrix[[0, 2]])

# Extract selected columns
print("\nSelected columns (2nd and 4th):" , matrix[:, [1, 3]])

# Transpose
print("\nTranspose:" , matrix.T)

# Row statistics
print("\nRow sum:" , np.sum(matrix, axis=1))

print("\nRow average:" , np.mean(matrix, axis=1))

# Column statistics
print("\nColumn sum:" , np.sum(matrix, axis=0))

print("\nColumn average:" , np.mean(matrix, axis=0))

# Identify unique values
print("\nUnique values:" , np.unique(matrix))

Original matrix:  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Selected rows (1st and 3rd): [[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]]

Selected columns (2nd and 4th): [[ 2  4]
 [ 8 10]
 [14 16]
 [20 22]]

Transpose: [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

Row sum: [ 21  57  93 129]

Row average: [ 3.5  9.5 15.5 21.5]

Column sum: [40 44 48 52 56 60]

Column average: [10. 11. 12. 13. 14. 15.]

Unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
